build: off

version: 1.0.{build}-{branch}

image: Visual Studio 2017

before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe

clone_folder: "c:\\project-m36"
clone_depth: 2
environment:
  global:
    STACK_ROOT: "c:\\sr"

platform:
 - x64

cache:
 - "c:\\sr"
 - "%LocalAppData%\\stack"

test_script:
 - stack setup > nul
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
 - echo "" | stack --no-terminal test
 - 7z.exe a project-m36.zip .stack-work\install\*\bin\*.exe

artifacts:
  - path: project-m36.zip
    name: project-m36.zip