# For more information, see https://github.com/ChrisPenner/haskell-stack-travis-ci
language: c
sudo: false

git:
  submodules: false  # whether to recursively clone submodules

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
    - .stack-work

matrix:
  fast_finish: true
  include:
    - env: CACHE_NAME=7.10.3 STACK_YAML=stack.ghc7.10.yaml GHC_VERSION=7.10.3
      compiler: ": #stack 7.10.3"
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}

    - env: CACHE_NAME=8.0.2 STACK_YAML=stack.yaml GHC_VERSION=8.0.2
      compiler: ": #stack 8.0.2"
      addons: {apt: {packages: [ghc-8.0.2], sources: [hvr-ghc]}}

    - env: CACHE_NAME=osx-7.10.3 STACK_YAML=stack.ghc7.10.yaml
      os: osx
      osx_image: xcode6.4
      compiler: ": #stack 7.10.3"

    - env: CACHE_NAME=osx-8.0.2 STACK_YAML=stack.yaml
      os: osx
      compiler: ": #stack 8.0.2"

#workaround for broken ruby in travis on mac https://github.com/travis-ci/travis-ci/issues/6307
before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get stable; fi

install:
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHC_VERSION/bin:$PATH
 - export IS_DARWIN=$([ $(uname) = "Darwin" ]; echo $?)
 - ./.travis/install-ghr.sh
 - ./.travis/install-stack.sh
 - GHC_VERSION=$GHC_VERSION ./.travis/install-ghc.sh


# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - |
   # Run tests
   if [[ $IS_DARWIN ]]; then
    stack --no-install-ghc --no-terminal test
   else
    stack --no-install-ghc --system-ghc --no-terminal test
   fi
 - [[ $IS_DARWIN = 0 ]] || curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s lint src test examples --cpp-define VERSION_project_m36=HLINT
 - [[ $IS_DARWIN = 0 ]] || stack --no-install-ghc haddock

after_success:
 - |
   # Build and ship binary
   #./.travis/attach-binary.sh

# EOF
