# For more information, see https://github.com/ChrisPenner/haskell-stack-travis-ci
language: c
sudo: false

git:
  submodules: false  # whether to recursively clone submodules

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
    - .stack-work

matrix:
  include:
    - env: CACHE_NAME=7.10.3 STACK_YAML=stack.ghc7.10.yaml
      compiler: ": #stack 7.10.3"

    - env: CACHE_NAME=8.0.2 STACK_YAML=stack.yaml
      compiler: ": #stack 8.0.2"

    - env: CACHE_NAME=osx-7.10.3 STACK_YAML=stack.ghc7.10.yaml
      os: osx
      compiler: ": #stack 7.10.3"

    - env: CACHE_NAME=osx-8.0.2 STACK_YAML=stack.yaml
      os: osx
      compiler: ": #stack 8.0.2"

install:
 - unset CC
 - export PATH=$HOME/.local/bin:$PATH
 - ./.travis/install-ghr.sh
 - ./.travis/install-stack.sh
 - travis_wait travis_retry stack setup
 - travis_retry stack build --only-dependencies

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - GHC_OPTIONS=""
 - |
   set -ex
   # Run tests
   stack --no-terminal test --ghc-options="$GHC_OPTIONS"
   set +ex

after_success:
 - |
   # Build and ship binary
   ./.travis/attach-binary.sh

# EOF
