# For more information, see https://github.com/ChrisPenner/haskell-stack-travis-ci
language: nix
sudo: false

git:
  submodules: false  # whether to recursively clone submodules

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
    - .stack-work

matrix:
  fast_finish: true
  include:
    - env: GHCVER=7.10.3 CACHE_NAME=7.10.3
      compiler: ": #stack 7.10.3"
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}

    - env: GHCVER=8.0.2 CACHE_NAME=8.0.2
      compiler: ": #stack 8.0.2"
      addons: {apt: {packages: [ghc-8.0.2], sources: [hvr-ghc]}}

    - env: GHCVER=8.2.1 CACHE_NAME=8.2.1 BUILD_BINARY=1
      compiler: ": #stack 8.2.1"
      addons: {apt: {packages: [ghc-8.2.1], sources: [hvr-ghc]}}

    - env: GHCVER=8.0.2 CACHE_NAME=8.0.2-osx BUILD_BINARY=1
      os: osx
      compiler: ": #stack 8.0.2"


#    - env: GHCVER=8.2.1 CACHE_NAME=8.2.1-osx BUILD_BINARY=1
#      os: osx
#      compiler: ": #stack 8.2.1"
#      addons: {apt: {packages: [ghc-8.2.1], sources: [hvr-ghc]}}

install:
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - ./.travis/install-ghr.sh
 - ./.travis/install-stack.sh

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - stack --no-terminal --system-ghc build 
 - stack --no-terminal --system-ghc test
 - stack --no-terminal --system-ghc haddock

#after_success:
# - |
#   # Build and ship binary
#   ./.travis/attach-binary.sh

# EOF
